<?php
/**
 * Setup WP-CLI configuration from .env file
 * Runs automatically after: composer install
 * Manual run: composer run-script setup-wp-cli
 * Force overwrite: php scripts/setup-wp-cli.php --force
 */

// Check for --force flag
$force = in_array('--force', $argv);

// Load .env file
if (!file_exists('.env')) {
    echo "⚠️  .env file not found. Skipping wp-cli.yml generation.\n";
    if (file_exists('.env.example.local')) {
        echo "💡 Copy .env.example.local to .env and run 'composer run-script setup-wp-cli' when ready.\n";
    } else {
        echo "💡 Copy .env.example to .env and run 'composer run-script setup-wp-cli' when ready.\n";
    }
    exit(0); // Exit gracefully, don't break install
}

$env = [];
$lines = file('.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

foreach ($lines as $line) {
    if (strpos($line, '=') !== false && !str_starts_with(trim($line), '#')) {
        [$key, $value] = explode('=', $line, 2);
        $env[trim($key)] = trim($value, '"\'');
    }
}

// Check required variables
$required = ['SERVER_USER', 'SERVER_IP', 'SERVER_BASE_PATH', 'PROD_DOMAIN', 'STAGING_DOMAIN'];
foreach ($required as $var) {
    if (!isset($env[$var])) {
        echo "❌ Missing required variable: $var in .env file\n";
        exit(1);
    }
}

// Check if wp-cli.yml already exists
if (file_exists('wp-cli.yml')) {
    $existing = file_get_contents('wp-cli.yml');
    
    // Check if it was auto-generated by this script
    if (!str_contains($existing, 'Auto-generated from .env variables')) {
        if ($force) {
            echo "⚠️  Forcing overwrite of custom wp-cli.yml...\n";
        } else {
            echo "⚠️  wp-cli.yml already exists and appears to be custom.\n";
            echo "❓ Do you want to overwrite it? This will REPLACE your current configuration.\n";
            echo "   [y/N]: ";
            
            $handle = fopen("php://stdin", "r");
            $line = fgets($handle);
            fclose($handle);
            
            if (trim(strtolower($line)) !== 'y') {
                echo "❌ Aborted. Your existing wp-cli.yml was not modified.\n";
                echo "💡 To use auto-generated config, rename your current file first:\n";
                echo "   mv wp-cli.yml wp-cli.yml.backup\n";
                echo "💡 Or force overwrite with: php scripts/setup-wp-cli.php --force\n";
                exit(0);
            }
        }
    } else {
        echo "🔄 Updating existing auto-generated wp-cli.yml...\n";
    }
}

// Generate wp-cli.yml
$wpCliConfig = <<<YML
# Auto-generated from .env variables
# Regenerate with: composer run-script setup-wp-cli

path: web/wp
server:
  docroot: web

@development:
  path: web/wp

@staging:
  ssh: {$env['SERVER_USER']}@{$env['SERVER_IP']}
  path: {$env['SERVER_BASE_PATH']}/{$env['STAGING_DOMAIN']}/web/wp

@production:
  ssh: {$env['SERVER_USER']}@{$env['SERVER_IP']}
  path: {$env['SERVER_BASE_PATH']}/{$env['PROD_DOMAIN']}/web/wp
YML;

file_put_contents('wp-cli.yml', $wpCliConfig);
echo "✅ wp-cli.yml generated successfully from .env variables\n";
?>